version: '3.8'

networks:
  eshop-network:
    driver: bridge

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-db
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - eshop-network

  apigateway:
    build: ./ApiGateway
    container_name: eshop-apigateway
    ports:
      - "5000:8080"    
    depends_on:
      - authservice
      - orderservice
      - productservice
    networks:
      - eshop-network

  authservice:
    build: ./AuthServiceApp
    container_name: eshop-authservice
    ports:
      - "5003:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db,1433;Database=AuthDb;User Id=sa;Password=YourPassword123!;Encrypt=False;"
      JwtSettings__Key: "aLongSuperSecretKeyWithAtLeast32Characters123!"
      JwtSettings__Issuer: "http://localhost"
      JwtSettings__Audience: "http://localhost"
    depends_on:
      - mssql-db  
    networks:
      - eshop-network
      
  orderservice:
    build: ./OrderServiceApp
    container_name: eshop-orderservice
    ports:
      - "5002:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db,1433;Database=OrderDb;User Id=sa;Password=YourPassword123!;Encrypt=False;"
    depends_on:
      - mssql-db
    networks:
      - eshop-network

  productservice:
    build: ./ProductServiceApp
    container_name: eshop-productservice
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db,1433;Database=ProductDb;User Id=sa;Password=YourPassword123!;Encrypt=False;"
    depends_on:
      - mssql-db
    networks:
      - eshop-network

  frontend:
    build: ./my-store
    container_name: eshop-frontend
    ports:
      - "3000:80"
    networks:
      - eshop-network